version: '3.8'

services:
  icecast:
    image: moul/icecast
    container_name: icecast
    ports:
      - "8000:8000"
    volumes:
      - ./icecast_config/icecast.xml:/etc/icecast_config/
    environment:
      - TZ=Europe/London
    restart: unless-stopped

  liquidsoap:
    image: savonet/liquidsoap:rolling-release-v2.3.x
    container_name: liquidsoap
    volumes:
      - ./liquidsoap/script.liq:/etc/liquidsoap   # Onde seu script.liq está localizado
      - /home/ubuntu/music/music:/music                 # Diretório com as músicas
    depends_on:
      - icecast
    command: liquidsoap /etc/liquidsoap/script.liq
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./landing_page/index.html:/usr/share/nginx/html
      - /home/ubuntu/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
    restart: unless-stopped