name: Deploy Online Radio

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # opcional: a cada hora, se quiser forçar atualização

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Adicionar chave de host do EC2
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 18.229.141.109 >> ~/.ssh/known_hosts


      - name: Criando repositorio
        run: |
          ssh ubuntu@18.229.141.109 "mkdir -p /home/ubuntu/online_radio"

      - name: Sincronizar arquivos para a instância EC2
        run: |
          rsync -avz --delete ./ ubuntu@18.229.141.109:/home/ubuntu/online_radio/
          
      - name: Reiniciar containers via Docker Compose
        run: |
          ssh ubuntu@18.229.141.109 "cd /home/ubuntu/online_radio && docker-compose down && docker-compose up -d"

